# Упражнение 11 (22.05.2020г.) - Изключения. Итератори.

## Изключения (Exceptions)
- `throw`, `try`, `catch`
- `std::exception`
- `catch ([type] ex)` / `catch (...)`

## Итератори
- `begin()`
- `end()`
- `advance(ptr, 3)`
- `next(ptr, 3)`
- `prev(ftr, 3)`
- `std::insert_iterator inserter(Container& c, typename Container::iterator i) `

[_Предишно упражнение_](../lab09-10)
